#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-addressable
Version  : 2.4.0
Release  : 7
URL      : https://rubygems.org/downloads/addressable-2.4.0.gem
Source0  : https://rubygems.org/downloads/addressable-2.4.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-coveralls
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support

%description
# Addressable
<dl>
<dt>Homepage</dt><dd><a href="https://github.com/sporkmonger/addressable">github.com/sporkmonger/addressable</a></dd>
<dt>Author</dt><dd><a href="mailto:bob@sporkmonger.com">Bob Aman</a></dd>
<dt>License</dt><dd>Apache 2.0</dd>
</dl>

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n addressable-2.4.0
gem spec %{SOURCE0} -l --ruby > rubygem-addressable.gemspec

%build
gem build rubygem-addressable.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
addressable-2.4.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/addressable-2.4.0
rspec -I.:lib spec/ || :
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/addressable-2.4.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/IDNA/PunycodeBadInput/cdesc-PunycodeBadInput.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/IDNA/PunycodeBigOutput/cdesc-PunycodeBigOutput.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/IDNA/PunycodeOverflow/cdesc-PunycodeOverflow.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/IDNA/cdesc-IDNA.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/IDNA/lookup_unicode_combining_class-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/IDNA/lookup_unicode_compatibility-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/IDNA/lookup_unicode_composition-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/IDNA/lookup_unicode_lowercase-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/IDNA/punycode_adapt-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/IDNA/punycode_basic%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/IDNA/punycode_decode-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/IDNA/punycode_decode_digit-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/IDNA/punycode_delimiter%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/IDNA/punycode_encode-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/IDNA/punycode_encode_digit-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/IDNA/to_ascii-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/IDNA/to_unicode-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/IDNA/unicode_compose-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/IDNA/unicode_compose_pair-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/IDNA/unicode_decompose-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/IDNA/unicode_decompose_hangul-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/IDNA/unicode_downcase-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/IDNA/unicode_normalize_kc-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/IDNA/unicode_sort_canonical-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/InvalidTemplateOperatorError/cdesc-InvalidTemplateOperatorError.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/InvalidTemplateValueError/cdesc-InvalidTemplateValueError.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/MatchData/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/MatchData/captures-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/MatchData/cdesc-MatchData.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/MatchData/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/MatchData/keys-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/MatchData/mapping-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/MatchData/names-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/MatchData/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/MatchData/post_match-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/MatchData/pre_match-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/MatchData/string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/MatchData/template-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/MatchData/to_a-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/MatchData/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/MatchData/uri-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/MatchData/values-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/MatchData/values_at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/MatchData/variables-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/TemplateOperatorAbortedError/cdesc-TemplateOperatorAbortedError.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/cdesc-Template.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/eql%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/expand-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/extract-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/freeze-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/generate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/join_values-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/keys-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/match-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/named_captures-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/names-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/normalize_keys-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/normalize_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/operator_sequence-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/ordered_variable_defaults-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/parse_template_pattern-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/partial_expand-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/pattern-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/processor/cdesc-processor.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/source-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/to_regexp-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/transform_capture-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/transform_partial_capture-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/variable_defaults-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/Template/variables-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/%2b-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/%3d%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/CharacterClasses/cdesc-CharacterClasses.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/InvalidURIError/cdesc-InvalidURIError.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/absolute%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/authority%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/authority-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/basename-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/cdesc-URI.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/convert_path-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/default_port-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/defer_validation-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/display_uri-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/dup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/empty%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/encode-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/encode_component-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/eql%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/escape-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/extname-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/form_encode-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/form_unencode-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/fragment%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/fragment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/freeze-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/heuristic_parse-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/host%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/host-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/hostname%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/hostname-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/inferred_port-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/ip_based%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/ip_based_schemes-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/join%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/join-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/join-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/merge%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/merge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/normalize%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/normalize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/normalize_component-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/normalize_path-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/normalized_authority-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/normalized_encode-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/normalized_fragment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/normalized_host-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/normalized_password-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/normalized_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/normalized_port-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/normalized_query-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/normalized_scheme-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/normalized_site-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/normalized_user-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/normalized_userinfo-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/omit%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/omit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/origin%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/origin-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/parse-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/password%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/password-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/path%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/port%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/port-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/port_mapping-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/query%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/query-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/query_values%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/query_values-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/relative%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/remove_composite_values-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/replace_self-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/request_uri%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/request_uri-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/route_from-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/route_to-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/scheme%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/scheme-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/site%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/site-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/split_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/to_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/to_str-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/unencode-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/unencode_component-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/unescape-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/unescape_component-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/user%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/user-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/userinfo%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/userinfo-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/URI/validate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/VERSION/cdesc-VERSION.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/Addressable/cdesc-Addressable.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/addressable-2.4.0/ri/page-README_md.ri
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/CHANGELOG.md
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/LICENSE.txt
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/README.md
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/addressable.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/data/unicode.data
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addressable.rb
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addressable/idna.rb
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addressable/idna/native.rb
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addressable/idna/pure.rb
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addressable/template.rb
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addressable/uri.rb
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addressable/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/spec/addressable/idna_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/spec/addressable/net_http_compat_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/spec/addressable/rack_mount_compat_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/spec/addressable/security_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/spec/addressable/template_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/spec/addressable/uri_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/tasks/clobber.rake
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/tasks/gem.rake
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/tasks/git.rake
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/tasks/metrics.rake
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/tasks/rspec.rake
/usr/lib64/ruby/gems/2.2.0/gems/addressable-2.4.0/tasks/yard.rake
/usr/lib64/ruby/gems/2.2.0/specifications/addressable-2.4.0.gemspec
